import React from "react";

export default function Form() {
  return (
    <div>
      <div>
        <input>NAME</input>
        <input>HEALTH</input>
        <input>ATTACK</input>
        <input>DEFENSE</input>
        <input>SPEED</input>
        <input>HEIGHT</input>
        <input>WEIGHT</input>
      </div>
      <div>
        <div>
          <h1>TYPE</h1>
        </div>
        <div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
          <div>
            <button></button>
            <h4>type</h4>
          </div>
        </div>
      </div>
    </div>
  );
}
